[package]
name = "runty8-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
runty8-core = { path = "../runty8-core" }
runty8-winit = { path = "../runty8-winit" }
winit = "0.27"
runty8-event-loop = { path = "../runty8-event-loop"}

[features]
steamdeck = ["runty8-event-loop/steamdeck"]
